Repository NabajitBhadury/Weather-Detector, pull requests merged in 2024-01, with the labels that each got.

#6 Update README.md
  README.md
Labels: easy, apertre24

#11 Bugfix/issue4 space between city name
  db.sqlite3
  weather/__pycache__/__init__.cpython-312.pyc
  weather/__pycache__/urls.cpython-312.pyc
  weather/__pycache__/views.cpython-312.pyc
  weather/views.py
  weatherdetector/__pycache__/__init__.cpython-312.pyc
  weatherdetector/__pycache__/settings.cpython-312.pyc
  weatherdetector/__pycache__/urls.cpython-312.pyc
  weatherdetector/__pycache__/wsgi.cpython-312.pyc
Labels: hard, apertre

#10 added footer of the website
  static/assets/css/style.css
  templates/index.html
  weather/__pycache__/__init__.cpython-312.pyc
  weather/__pycache__/urls.cpython-312.pyc
  weather/__pycache__/views.cpython-312.pyc
  weatherdetector/__pycache__/__init__.cpython-312.pyc
  weatherdetector/__pycache__/settings.cpython-312.pyc
  weatherdetector/__pycache__/urls.cpython-312.pyc
  weatherdetector/__pycache__/wsgi.cpython-312.pyc
Labels: easy, apertre

#13 City not found 404 response code exception handled
  static/assets/css/style.css
  templates/index.html
  weather/views.py
Labels: easy, apertre

#15 Update README.md
  README.md
Labels: easy, apertre
